name: Deploy Dev Stage

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      ADMIN_SECRET_PHRASE: ${{ secrets.ADMIN_SECRET_PHRASE }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      AWS_REGION: us-east-2
      STAGE: dev
      CLOUDINARY_TARGET_FOLDER: pollogram-api-hono-dev
      DATABASE_URL: ${{ secrets.DATABASE_URL_DEV }}
      DATABASE_URL_UNPOOLED: ${{ secrets.DATABASE_URL_UNPOOLED_DEV }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.14'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Deploy
        run: pnpm ga:deploy:dev
